### ISSUE TITLE
The training and inference code

### ISSUE THREAD

**Issue by zijinY** [phamtienkha/generative-pseudoinverse-memory#1]
Sincerely appreciate your fancy work on the external memory! 
I want to utilize your memory code on other datasets and induce more analysis of intrinsic properties, would you like to provide the training and inference code? 👍

**Comment by phamtienkha** [comment]
Hi. I've just added the main.py file, which includes the training code (for the Omniglot dataset; it's almost the same for other datasets). I also added functions for denoising and generating images in model.py. Hope it can help!
